# BASE stage
FROM node:22 AS base
WORKDIR /usr/local/app
COPY package*.json .
RUN npm ci 

# PROD stage
FROM base AS prod
WORKDIR /usr/local/app
COPY package*.json .
RUN npm install --omit=dev
COPY . .
CMD ["npm", "run", "start"]
EXPOSE 3000