# BASE stage
FROM node:22 AS base
WORKDIR /usr/local/app
COPY package*.json .
RUN npm ci 

# TEST stage
FROM base AS test
COPY . .
CMD ["npm", "test"]

# PROD stage
FROM node:22 AS prod
WORKDIR /usr/local/app
COPY package*.json .
RUN npm install --omit=dev
COPY . .
CMD ["npm", "run", "start"]
EXPOSE 3000